export {
  ITEM_CLASS_BY_SUBTYPE,
  ITEM_CLASS_IDS,
  ITEM_CONDITION_IDS,
  ITEM_GLOW_MODE_IDS,
  ITEM_MATERIAL_IDS,
  ITEM_PRESENTATION_IDS,
  ITEM_PURPOSE_IDS,
  ITEM_READABILITY_IDS,
  ITEM_SHADOW_MODE_IDS,
  ITEM_SIGNIFICANCE_IDS,
  ITEM_SIZE_IDS,
  ITEM_WEAR_POSITION_IDS,
  WEARABLE_ITEM_SUBTYPES,
  getDefaultItemClass,
  itemSubtypeSupportsWearPosition,
  type ItemClass,
  type ItemCondition,
  type ItemGlowMode,
  type ItemMaterial,
  type ItemPresentation,
  type ItemPurpose,
  type ItemReadability,
  type ItemShadowMode,
  type ItemSignificance,
  type ItemSize,
  type ItemSubtype,
  type ItemWearPosition
} from "./item.types";
