export {
  EXTREME_SCALE_WARNING_MAX,
  EXTREME_SCALE_WARNING_MIN,
  SOURCE_ANCHOR_ISSUE_CODES,
  SOURCE_VECTOR_EPSILON,
  applyTransformDelta,
  resolveBonePlacement,
  resolveEffectiveAnchor,
  snapSourcePoint,
  toSourceAnchors,
  validateSourceAnchors,
  type AdjustedBonePlacement,
  type BonePlacement,
  type BonePlacementResult,
  type BonePlacementWarning,
  type EditableSourceAnchors,
  type ResolveBonePlacementInput,
  type SourceAnchorIssue,
  type SourceAnchorIssueCode,
  type SourceAnchorValidationResult
} from "./anchorPlacement";
export {
  FRAME_OVERRIDE_MAX_OFFSET,
  FRAME_OVERRIDE_MAX_ROTATION,
  FRAME_OVERRIDE_MAX_SCALE,
  FRAME_OVERRIDE_MIN_SCALE,
  FRAME_OVERRIDE_OFFSET_WARNING,
  FRAME_OVERRIDE_ROTATION_WARNING,
  FRAME_OVERRIDE_MAX_SCALE_WARNING,
  FRAME_OVERRIDE_MIN_SCALE_WARNING,
  IDENTITY_FRAME_DELTA,
  applyFrameLayerOrder,
  collectFrameOverrideWarnings,
  diffFrameFromGeneratedBaseline,
  findFrameOverride,
  frameOverrideMatches,
  isNeutralFrameDelta,
  normalizeFrameOverride,
  removeFrameOverride,
  resetDirectionOverrides,
  resetFrameOverride,
  resolveEffectiveFramePose,
  upsertFrameOverride,
  type EffectiveFramePose,
  type FrameOverride,
  type FrameOverrideAddress,
  type GeneratedFramePose
} from "./frameOverrides";
export {
  DEFAULT_ALPHA_THRESHOLD,
  cropRgba,
  findAlphaBounds,
  hasOpaqueOuterEdge,
  type RgbaImage
} from "./rgba";
export {
  ANIMATION_ACTION_IDS,
  MIRROR_POLICIES,
  RIG_TEMPLATE_IDS,
  type AnimationActionId,
  type FrameProfile,
  type MirrorPolicy,
  type Point,
  type Rect,
  type RigTemplateId,
  type Size,
  type SourceAnchors,
  type Transform2D,
  type TransformDelta
} from "./animation.types";
export {
  DIRECTION_IDS,
  DIRECTION_SOURCE_MODES,
  getMirroredDirection,
  getOppositeDirection,
  getRequiredAuthoredDirections,
  isAuthoredDirectionForMode,
  isDirection,
  type Direction,
  type DirectionSourceMode
} from "./directions";
export {
  MIRRORED_DIRECTION_SOURCE,
  getMirroredSourceDirection,
  mirrorDirectionRig,
  mirrorFramePoint,
  mirrorRgbaImage,
  mirrorSourceAnchors,
  mirrorSourcePoint,
  mirrorSourceRect,
  mirrorSourceX,
  mirrorTransformDelta,
  resolveDirectionRig,
  resolveRuntimeDirectionRig,
  type MirroredTargetDirection,
  type RuntimeDirectionRigResolution
} from "./directionProjection";
export {
  DIRECTION_COVERAGE_STATUSES,
  partRequiresMirrorReview,
  resolveDirectionSource,
  resolveProjectDirectionCoverage,
  validateMirrorPolicy,
  type DirectionCoverageStatus,
  type DirectionMirrorReview,
  type DirectionSourceAsset,
  type DirectionSourceResolution,
  type EffectiveMirrorPolicy,
  type MirrorPolicySource,
  type MirrorPolicyValidation,
  type ProjectDirectionCoverage,
  type ProjectDirectionCoverageRow,
  type ResolveDirectionSourceInput
} from "./coverage";
export {
  ANCHOR_CONTRACT_VERSION,
  DIRECTION_CONTRACT_VERSION,
  HUMANOID_80_FRAME_PROFILE,
  HUMANOID_80_RIG_TEMPLATE_ID,
  REQUIRED_SLOT_CONTRACT_VERSION
} from "./frameProfiles";
export {
  BUILT_IN_RIG_TEMPLATES,
  HUMANOID_80_BONES,
  HUMANOID_80_DIRECTION_RIGS,
  HUMANOID_80_RIG_TEMPLATE,
  HUMANOID_80_SLOT_BINDINGS,
  getBuiltInRigTemplate,
  isRigSourceDirection
} from "./humanoidRig80";
export {
  AFFINE_DETERMINANT_EPSILON,
  IDENTITY_TRANSFORM,
  applyTransform,
  composeTransforms,
  createRotationTransform,
  createTranslationTransform,
  createUniformScaleTransform,
  invertTransform
} from "./matrices";
export {
  DEFAULT_FREE_ACCESSORY_LAYER_GROUP,
  DEFAULT_OPTIONAL_SLOT_ATTACHMENT_JOINTS,
  DIRECTION_DRAW_ORDERS,
  DRAW_ORDER_ISSUE_CODES,
  DRAW_ORDER_VERSION,
  LAYER_GROUPS,
  MAX_PROJECT_LAYER_OFFSET,
  MIN_PROJECT_LAYER_OFFSET,
  getDefaultLayerGroup,
  getDirectionDrawOrder,
  isFreeAccessorySlot,
  resolveDirectionDrawOrder,
  resolvePartAttachmentJoint,
  validateDrawOrder,
  type AnatomicalSide,
  type AttachmentJoint,
  type DirectionDrawOrder,
  type DirectionLayerEntry,
  type DrawOrderIssue,
  type DrawOrderIssueCode,
  type DrawOrderValidationResult,
  type LayerGroup,
  type LayeredPart,
  type ResolveDirectionDrawOrderResult,
  type ResolvedLayeredPart,
  type VisualNearSide
} from "./layerOrder";
export {
  RASTER_COORDINATE_EPSILON,
  RENDER_DIAGNOSTIC_CODES,
  blitNearestAffine,
  compositeSourceOver,
  createRasterSurface,
  renderFrame,
  renderPart,
  type RasterBlitResult,
  type RasterBounds,
  type RasterSurface,
  type FrameEdge,
  type RenderDiagnostic,
  type RenderDiagnosticCode,
  type RenderablePart,
  type RenderedFrame,
  type RgbaPixel
} from "./renderer";
export {
  BONE_IDS,
  BONE_TOPOLOGY,
  BONE_TOPOLOGY_BY_ID,
  JOINT_IDS,
  REQUIRED_SLOT_JOINT_BINDINGS,
  isBoneId,
  isJointId,
  type BoneId,
  type BoneTopologyDefinition,
  type JointId,
  type RequiredSlotJointBinding,
  type SourceAnchorRequirement
} from "./rigTopology";
export {
  RIG_COORDINATE_EPSILON,
  RIG_GROUNDLINE_TOLERANCE,
  RIG_SOURCE_DIRECTION_IDS,
  RIG_VALIDATION_ISSUE_CODES,
  createRigCompatibilityKey,
  findDirectionRig,
  findSlotBinding,
  validateRigTemplate,
  type BoneDefinition,
  type BoneRole,
  type DirectionMotionProfile,
  type DirectionRig,
  type JointDefinition,
  type RigNearSide,
  type RigProjection,
  type RigSourceDirection,
  type RigTemplate,
  type RigValidationIssue,
  type RigValidationIssueCode,
  type RigValidationResult,
  type SlotBinding
} from "./rigTemplate";
export {
  OPTIONAL_PART_SLOT_IDS,
  PART_SLOT_DEFINITIONS,
  PART_SLOT_GROUP_IDS,
  PART_SLOT_GROUPS,
  PART_SLOT_IDS,
  REQUIRED_PART_SLOT_IDS,
  isPartSlot,
  isRequiredPartSlot,
  type OptionalPartSlot,
  type PartSlot,
  type PartSlotDefinition,
  type PartSlotGroupDefinition,
  type PartSlotGroupId,
  type RequiredPartSlot
} from "./slots";
export {
  addVectors,
  clamp,
  normalizeAngle,
  subtractVectors,
  vectorAngle,
  vectorLength
} from "./vectors";
export {
  HUMANOID_WALK_CHANNELS,
  HUMANOID_WALK_CLIP,
  HUMANOID_WALK_CLIP_ID,
  HUMANOID_WALK_CLIP_VERSION,
  HUMANOID_WALK_DEFAULT_FPS,
  HUMANOID_WALK_FRAME_COUNT,
  HUMANOID_WALK_LOOP,
  HUMANOID_WALK_PHASES,
  TWO_BONE_IK_DIAGNOSTIC_CODES,
  TWO_BONE_IK_EPSILON,
  WALK_POSE_ISSUE_CODES,
  WALK_ROOT_BOB_LIMIT,
  applyPoseToDirectionRig,
  resolveClipFrame,
  projectWalkChannels,
  resolveDirectionalWalkPose,
  resolveHumanoidWalkPose,
  solveTwoBoneIk,
  validatePose,
  type AppliedHumanoidWalkPose,
  type ApplyHumanoidWalkPoseResult,
  type HumanoidSide,
  type HumanoidWalkChannels,
  type HumanoidWalkClipTemplate,
  type HumanoidWalkPhaseId,
  type HumanoidWalkPose,
  type DirectionalWalkPose,
  type ProjectedWalkChannels,
  type ResolvedHumanoidWalkFrame,
  type TwoBoneIkDiagnostic,
  type TwoBoneIkDiagnosticCode,
  type TwoBoneIkInput,
  type TwoBoneIkResult,
  type WalkPoseIssue,
  type WalkPoseIssueCode,
  type WalkPoseValidationResult
} from "./walkClip";
