export {
  TEXTURE_CONDITION_IDS,
  TEXTURE_ICING_IDS,
  TEXTURE_LIGHTING_IDS,
  TEXTURE_MATERIAL_TYPE_BY_SUBTYPE,
  TEXTURE_MATERIAL_TYPE_IDS,
  TEXTURE_MOISTURE_IDS,
  TEXTURE_ORIENTATION_IDS,
  TEXTURE_STRUCTURE_IDS,
  TEXTURE_SURFACE_IDS,
  TEXTURE_USAGE_IDS,
  getDefaultTextureMaterialType,
  type TextureCondition,
  type TextureIcing,
  type TextureLighting,
  type TextureMaterialType,
  type TextureMoisture,
  type TextureOrientation,
  type TextureStructure,
  type TextureSubtype,
  type TextureSurface,
  type TextureUsage
} from "./texture.types";
